name: Configure and Build

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, macos-13, macos-latest]
        c_compiler: [gcc, clang]

    steps:
      - uses: actions/checkout@v3
      - name: autogen/configure
        run: ./autogen.sh
      - name: configure
        run: ./configure CC="${{ matrix.c_compiler }}" --prefix="${{ github.workspace }}/build"
      - name: make
        run: make all
