name: Configure and Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Configure and Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, macos-13, macos-latest]
        c_compiler: [gcc-10, clang]

    steps:
      - uses: actions/checkout@v3
      - uses: ConorMacBride/install-package@v1
        with:
          brew: gettext autoconf automake libtool openssl
          apt: build-essential autopoint automake autoconf libssl-dev libtool gettext
      - name: Install compiler
        id: install_cc
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: ${{ matrix.c_compiler }}
      - name: Fix gettext on macOS
        if: runner.os == 'macOS'
        run: |
          export GETTEXT_PATH=$(brew --prefix gettext)
          export LDFLAGS="-L${GETTEXT_PATH}/lib $LDFLAGS"
          export CPPFLAGS="-I${GETTEXT_PATH}/include"
      - name: autogen/configure
        run: ./autogen.sh
      - name: configure
        run: ./configure CC="${{ steps.install_cc.outputs.cc }}" --prefix="${{ github.workspace }}/build"
      - name: make
        run: make all
